
#include <stdio.h>
#include <stdlib.h>
#include <math.h>

#define NFOUND  -1
#define FOUND   0
#define BREAK   1
#define NBREAK  2
#define RIGHT   3
#define LEFT    4
#define UP      5
#define DOWN    6

#define ARR_SIZE_X  20
#define ARR_SIZE_Y  20

void
show (int (*)[ARR_SIZE_X]);

int *
search (int (*)[ARR_SIZE_X], int, int, int, int);

int
calculateJump (int, int);

/*
int arr[ARR_SIZE_Y][ARR_SIZE_X] = {
    {NBREAK,NBREAK,NBREAK,UP,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK},\
    {NBREAK,NBREAK,NBREAK,UP,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK},\
    {NBREAK,NBREAK,NBREAK,UP,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK},\
    {NBREAK,NBREAK,NBREAK,UP,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK},\
    {RIGHT,RIGHT,RIGHT,FOUND,LEFT,LEFT,LEFT,LEFT,LEFT,LEFT},\
    {BREAK,BREAK,BREAK,DOWN,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK},\
    {BREAK,BREAK,BREAK,DOWN,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK},\
    {BREAK,BREAK,BREAK,DOWN,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK},\
    {BREAK,BREAK,BREAK,DOWN,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK},\
    {BREAK,BREAK,BREAK,DOWN,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK}
};
*/

int arr[ARR_SIZE_Y][ARR_SIZE_X] = {
    {NBREAK,NBREAK,NBREAK,NBREAK,NBREAK,NBREAK,NBREAK,NBREAK,NBREAK,UP,\
    BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK},\
    {NBREAK,NBREAK,NBREAK,NBREAK,NBREAK,NBREAK,NBREAK,NBREAK,NBREAK,UP,\
    BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK},\
    {NBREAK,NBREAK,NBREAK,NBREAK,NBREAK,NBREAK,NBREAK,NBREAK,NBREAK,UP,\
    BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK},\
    {NBREAK,NBREAK,NBREAK,NBREAK,NBREAK,NBREAK,NBREAK,NBREAK,NBREAK,UP,\
    BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK},\
    {NBREAK,NBREAK,NBREAK,NBREAK,NBREAK,NBREAK,NBREAK,NBREAK,NBREAK,UP,\
    BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK},\
    {NBREAK,NBREAK,NBREAK,NBREAK,NBREAK,NBREAK,NBREAK,NBREAK,NBREAK,UP,\
    BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK},\
    {NBREAK,NBREAK,NBREAK,NBREAK,NBREAK,NBREAK,NBREAK,NBREAK,NBREAK,UP,\
    BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK},\
    {NBREAK,NBREAK,NBREAK,NBREAK,NBREAK,NBREAK,NBREAK,NBREAK,NBREAK,UP,\
    BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK},\
    {NBREAK,NBREAK,NBREAK,NBREAK,NBREAK,NBREAK,NBREAK,NBREAK,NBREAK,UP,\
    BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK},\
    {NBREAK,NBREAK,NBREAK,NBREAK,NBREAK,NBREAK,NBREAK,NBREAK,NBREAK,UP,\
    BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK},\
    {NBREAK,NBREAK,NBREAK,NBREAK,NBREAK,NBREAK,NBREAK,NBREAK,NBREAK,UP,\
    BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK},\
    {NBREAK,NBREAK,NBREAK,NBREAK,NBREAK,NBREAK,NBREAK,NBREAK,NBREAK,UP,\
    BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK},\
    {NBREAK,NBREAK,NBREAK,NBREAK,NBREAK,NBREAK,NBREAK,NBREAK,NBREAK,UP,\
    BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK},\
    {NBREAK,NBREAK,NBREAK,NBREAK,NBREAK,NBREAK,NBREAK,NBREAK,NBREAK,UP,\
    BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK},\
    {RIGHT,RIGHT,RIGHT,RIGHT,RIGHT,RIGHT,RIGHT,RIGHT,RIGHT,FOUND,\
    LEFT,LEFT,LEFT,LEFT,LEFT,LEFT,LEFT,LEFT,LEFT,LEFT},\
    {BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,DOWN,\
    BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK},\
    {BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,DOWN,\
    BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK},\
    {BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,DOWN,\
    BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK},\
    {BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,DOWN,\
    BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK},\
    {BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,DOWN,\
    BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK,BREAK}
};

int
main (void)
{
    show (arr);
    int *res = search (arr, 0, ARR_SIZE_X-1, 0, ARR_SIZE_Y-1);
    printf ("x=%d y=%d\n", res[0], res[1]);
    free (res);
    return 0;
}

void
show (int (*arr)[ARR_SIZE_X])
{
    for (int j = 0; j < ARR_SIZE_Y; j++)
    {
        for (int i = 0; i < ARR_SIZE_X; i++)
        {
            printf ("%d ", arr[j][i]);
        }
        printf ("\n");
    }
}

int
calculateJump (int min, int max)
{
    if (min==max) return min;
    return (max+min)/2;
}

int *
search (int (*arr)[ARR_SIZE_X], int left, int right, int down, int up)
{
    int *res=NULL;
    int j_x = calculateJump (left, right);
    int j_y = calculateJump (down, up);
    switch ( arr[j_y][j_x] )
    {
        case NBREAK:
            res = search (arr, j_x+1, right, j_y+1, up);
            break;
        case BREAK:
            res = search (arr, left, j_x-1, down, j_y-1);
            break;
        case RIGHT:
            res = search (arr, j_x+1, right, j_y, j_y);
            break;
        case LEFT:
            res = search (arr, left, j_x-1, j_y, j_y);
            break;
        case UP:
            res = search (arr, j_x, j_x, j_y+1, up);
            break;
        case DOWN:
            res = search (arr, j_x, j_x, down, j_y-1);
            break;
        case FOUND: 
            res = (int *)malloc (sizeof(int)*2);
            res[0] = j_x;
            res[1] = j_y;
            return res;
    }
    return res;
}
